spring:
  config:
    import:
      - optional:file:.env[.properties]

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: app-route-v1
              uri: ${APP_SERVICE_URL}
              predicates:
                - Path=${APP_v1_PATH_URL}
            - id: app-route-v2
              uri: ${APP_SERVICE_URL}
              predicates:
                - Path=${APP_v2_PATH_URL}
            - id: app-route-v3
              uri: ${APP_SERVICE_URL}
              predicates:
                - Path=${APP_v3_PATH_URL}
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  jwt:
    key: ${JWT_KEY}
    access_exp_time: ${JWT_ACCESS_EXP_TIME}
    refresh_exp_time: ${JWT_REFRESH_EXP_TIME}

security:
  whitelist:
    paths:
      - ${LOGIN_URL}
      - ${REFRESH_URL}
      - ${H2_CONSOLE_URL}
      - ${ACTUATOR_URL}
      - ${API_SWAGGER_URL}
      - ${API_V3_DOCS_URL}
      - ${SWAGGER_URL}
      - ${API_DOCS_URL}
