spring:
  config:
    import:
      - optional:file:.env[.properties]

  cloud:
    gateway:
      routes:
        - id: app-route
          uri: ${APP_SERVICE_URL}
          predicates:
            - Path=${APP_PATH_URL}
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  jwt:
    key: ${JWT_KEY}
    access_exp_time: ${JWT_ACCESS_EXP_TIME}
    refresh_exp_time: ${JWT_REFRESH_EXP_TIME}

security:
  whitelist:
    paths:
      - ${LOGIN_URL}
      - ${REFRESH_URL}
      - ${H2_CONSOLE_URL}
      - ${ACTUATOR_URL}
      - ${API_SWAGGER_URL}
      - ${API_V3_DOCS_URL}
      - ${SWAGGER_URL}
      - ${API_DOCS_URL}
